name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }} / Testbench ${{ matrix.testbench }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.0'
            testbench: '3.0.*'
            phpunit: '~4.8.36'
          - php: '7.1'
            testbench: '3.5.*'
            phpunit: '~6.0'
          - php: '7.2'
            testbench: '3.8.*'
            phpunit: '^7.5'
          - php: '7.3'
            testbench: '^4.0'
            phpunit: '^8.0'
          - php: '7.4'
            testbench: '^5.0'
            phpunit: '^8.5'
          - php: '8.0'
            testbench: '^6.0'
            phpunit: '^9.0'
          - php: '8.1'
            testbench: '^7.0'
            phpunit: '^9.5'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl
          coverage: none
          tools: composer:v2.2

      - name: Validate Composer metadata
        run: composer validate --strict

      - name: Select test dependencies
        run: composer require orchestra/testbench:${{ matrix.testbench }} phpunit/phpunit:${{ matrix.phpunit }} --no-update --no-interaction --dev

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
        env:
          COMPOSER_MEMORY_LIMIT: -1

      - name: Run tests
        run: composer test
